/*
 * Globalping API
 *
 * The Globalping API allows you to monitor, debug, and benchmark your internet infrastructure using a globally distributed network of probes.  The API is public, free to use, and doesn't require authentication. However, it implements rate limits to ensure fair usage and reliability, and some of the limits are higher for authenticated users. Sign up on the [Globalping Dashboard](https://dash.globalping.io/) to enjoy the higher limits.  Root endpoint: https://api.globalping.io  ## Limits and credits  | Operation | Unauthenticated user | Authenticated user | |---|---|---| | **Measurements** ||| | Create a measurement | 250 tests/hour | 500 tests/hour* | | Get a measurement by ID | 2 requests/second/measurement | 2 requests/second/measurement | | **Probes** ||| | List probes currently online | no limit | no limit | | **Limits** ||| | Get current rate limits | no limit | no limit |  \\*Additional measurements may be created by spending credits. Each test above the limit costs one credit. Learn more about credits on the [Globalping website](https://globalping.io/credits).  ## Client guidelines  If you're implementing an application that interacts with the API, please refer to the \"Client guidelines\" section in the description of each endpoint. This way, you can provide the best UX and reduce the likelihood of your app breaking in the future.  ### General guidelines for non-browser-based apps:  - Set a `User-Agent` header. We recommend that you follow the format and approach [used here](https://github.com/jsdelivr/data.jsdelivr.com/blob/60c5154d26c403ba9dd403a8ddc5e42a31931f0d/config/default.js#L9). - Set an `Accept-Encoding` header with a value of either `br` (preferred) or `gzip`, depending on what your client can support. Compression has a significant impact on the response size. - Implement ETag-based client-side caching using the `ETag`/`If-None-Match` headers when requesting the measurement status. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: d@globalping.io
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    /// The measurement ID.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: models::MeasurementType,
    /// A publicly reachable measurement target. Typically a hostname, an IPv4 address, or IPv6 address, depending on the measurement `type`. Support for IPv6 targets is currently considered experimental. 
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "status")]
    pub status: models::MeasurementStatus,
    /// The date and time when the measurement was created.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The date and time when the measurement was last updated.
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    /// The actual number of probes that performed the measurement tests. Smaller or equal to `limit`, depending on probe availability. 
    #[serde(rename = "probesCount")]
    pub probes_count: i32,
    /// The locations you specified when creating the measurement. If you passed in an `id` of a previous measurement, the value will be filled in from that measurement. 
    #[serde(rename = "locations", skip_serializing_if = "Option::is_none")]
    pub locations: Option<Vec<models::MeasurementLocationOption>>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Box<i32>>,
    #[serde(rename = "measurementOptions", skip_serializing_if = "Option::is_none")]
    pub measurement_options: Option<Box<models::MeasurementResponseMeasurementOptions>>,
    /// An array containing the measurement results.
    #[serde(rename = "results")]
    pub results: Vec<models::MeasurementResultItem>,
}

impl InlineObject2 {
    pub fn new(id: String, r#type: models::MeasurementType, target: String, status: models::MeasurementStatus, created_at: String, updated_at: String, probes_count: i32, results: Vec<models::MeasurementResultItem>) -> InlineObject2 {
        InlineObject2 {
            id,
            r#type,
            target,
            status,
            created_at,
            updated_at,
            probes_count,
            locations: None,
            limit: None,
            measurement_options: None,
            results,
        }
    }
}

