name: "dev-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Dev Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build -r

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/release/opti-hosts
